### ISSUE TITLE
Questions about the experimental part of the thesis

### ISSUE THREAD

**Issue by QianZhao-xd** [011235813/hierarchical-marl#1]
Dear Dr.
      I'm sorry to bother you, I've been conducting experiments on the paper "Hierarchical Cooperative Multi-Agent Reinforcement Learning with Skill Discovery", but I'm not sure how to do the experiments on the projection of each skill's action distribution via PCA as shown in Fig. 2 of the paper. I would greatly appreciate your guidance on how to conduct this specific experiment. Thank you very much for your time and assistance. I look forward to your reply.

**Comment by 011235813** [comment]
To get a PCA plot from the data of action counts (e.g, to get Fig 2d from the data in Fig 2c), we treated each skill as a vector with 9 dimensions (corresponding to the 9 possible actions), then applied PCA to the set of four vectors (one for each skill) to reduce to 2 dimensions.
